const fs = require('fs');

const dataStr = `[
    {
        "id": "ba73991e-8d01-48c4-b1af-98ea861aaa11",
        "name": "Dharitri Mohan",
        "district": "Sivasagar",
        "location": "Betbari 2no Dow gaon ",
        "contact_number": "9864194854",
        "num_people": 5,
        "needs": ["medical"],
        "needs_other": "Mattress, garu  tripal athua",
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": true,
        "live_lat": 27.021737,
        "live_lng": 94.7078697,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T15:49:44.286024+00:00",
        "lat": 27.021737,
        "lng": 94.7078697,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "8d12978b-48cf-4be6-af44-ec13199d0966",
        "name": "Dipu",
        "district": "Sivasagar",
        "location": "Nimaijaan",
        "contact_number": "6001606467",
        "num_people": 1,
        "needs": ["water", "food", "clothes", "medical", "sanitation", "baby_care"],
        "needs_other": null,
        "priority": "urgent",
        "boat_required": null,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T15:42:06.003074+00:00",
        "lat": 26.9932073823165,
        "lng": 94.6710978609259,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "0fcf3aef-906e-483a-9bc7-bc135293e5d3",
        "name": "Parag Boruah",
        "district": "Sivasagar",
        "location": "Bamunbari, 3no. Ward, Near Bamunbari Namghor / 548 no. Bamunbari Lower Pimery School. ",
        "contact_number": "8830637346",
        "num_people": 500,
        "needs": ["water", "food", "clothes", "baby_care", "sanitation"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "On foot",
        "has_live_location": true,
        "live_lat": 26.9009009009009,
        "live_lng": 94.5966214584467,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T13:00:43.163001+00:00",
        "lat": 26.9009009009009,
        "lng": 94.5966214584467,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "47b631ed-3559-4846-a42f-65c45ff7a579",
        "name": "Archana Gayan saikia",
        "district": "Sivasagar",
        "location": "Jaluk goan, chwadang ward",
        "contact_number": "7637987330",
        "num_people": 1,
        "needs": ["food", "clothes"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T13:00:36.259487+00:00",
        "lat": 26.9857355514577,
        "lng": 94.6519307849969,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "ba10ee6d-16c2-4e42-8a7a-f0e0bd457a45",
        "name": "Dipankar das",
        "district": "Charaideo",
        "location": "Naphuk gaon . Navajyoti lp school ",
        "contact_number": "8011846871",
        "num_people": 70,
        "needs": ["food"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "Amrar এয়াৰ relif laga gaon khobor obostha baya ase manuha kam puwa ni , pindhibo Kapur ni aru khuwa panir problem kiba ata help pala bhal hoi",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T11:57:19.261197+00:00",
        "lat": 27.0656154844768,
        "lng": 95.0294882446366,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "1e7cc748-000e-4476-898f-b88dda70553e",
        "name": "Arun Saikia",
        "district": "Sivasagar",
        "location": "Pohuchungi Deodhai Bharaluwa gaon,Near gargaon ITI",
        "contact_number": "9101985049",
        "num_people": 10,
        "needs": [],
        "needs_other": "Animal food and grass",
        "priority": "needed",
        "boat_required": false,
        "notes": "No",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T10:36:06.245446+00:00",
        "lat": 27.0195046552944,
        "lng": 94.6745518615114,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "7a1fdf8e-f627-449b-ae21-92f978354030",
        "name": "Dilip Dutta",
        "district": "Sivasagar",
        "location": "Panibill, gomutha, village \nSunpura Road ",
        "contact_number": "9435730974",
        "num_people": 1,
        "needs": [],
        "needs_other": "Kitchen items ",
        "priority": "urgent",
        "boat_required": false,
        "notes": "No",
        "has_live_location": true,
        "live_lat": 26.9880838,
        "live_lng": 94.6215992,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T10:21:38.786516+00:00",
        "lat": 26.9880838,
        "lng": 94.6215992,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "21b82231-04e5-456e-89da-670bf07e8028",
        "name": "Priyanka chetia ",
        "district": "Sivasagar",
        "location": "Betbari Borkuri chetia goan ",
        "contact_number": "8486433980",
        "num_people": 5,
        "needs": [],
        "needs_other": "I needed help for studying.A chair to sit and a study table to read books.",
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": true,
        "live_lat": 27.0193296,
        "live_lng": 94.7030212,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T09:43:49.726076+00:00",
        "lat": 27.0193296,
        "lng": 94.7030212,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "c97cc93d-de13-40af-b4dc-a26d5caa628c",
        "name": "Ezaz Ahmed ",
        "district": "Sivasagar",
        "location": "Nazia ward no 4",
        "contact_number": "9101440481",
        "num_people": 70,
        "needs": ["food"],
        "needs_other": null,
        "priority": "urgent",
        "boat_required": true,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T09:27:58.145723+00:00",
        "lat": 27.0177980302493,
        "lng": 94.6517421660645,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "4858ad61-f63e-426b-9da9-c50db3cf07b7",
        "name": "Tutumoni das",
        "district": "Sivasagar",
        "location": "2no. Bhuyanhat gaon, Amguri",
        "contact_number": "6900565405",
        "num_people": 4,
        "needs": ["water"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": true,
        "live_lat": 26.8218406,
        "live_lng": 94.4975218,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T08:48:50.019098+00:00",
        "lat": 26.8218406,
        "lng": 94.4975218,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "0d48e342-8c99-43e3-98fd-9dfedd4629b8",
        "name": "Mr Rahul Panging ",
        "district": "Sivasagar",
        "location": "Alimur Gyanudoy High School,Khanmaukh.",
        "contact_number": "7086429670",
        "num_people": 5,
        "needs": ["water", "food", "clothes", "medical", "sanitation", "baby_care"],
        "needs_other": null,
        "priority": "urgent",
        "boat_required": null,
        "notes": "📍 Urgent Requirements of \n1.  Buckets\n2. Mugs\n3. Phenyl \n4. Other sanitation products.",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T08:27:33.41538+00:00",
        "lat": 26.9847614653232,
        "lng": 94.6348019014329,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "8e419d37-7dfe-457e-af90-65745faba23d",
        "name": "Mantu Naidu",
        "district": "Jorhat",
        "location": "Bamunpukhuri bora goan",
        "contact_number": "7086707658",
        "num_people": 4,
        "needs": ["clothes", "medical", "food", "water"],
        "needs_other": null,
        "priority": "urgent",
        "boat_required": false,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T07:06:13.111618+00:00",
        "lat": 26.7375698402562,
        "lng": 94.2469101785226,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "9684415a-a151-4bd9-8ce3-01ed9acfb2f8",
        "name": "Sudarkhina Chutia ",
        "district": "Sivasagar",
        "location": "Konwerpur boliaghat, baghorchuk majgon ",
        "contact_number": "9707791496",
        "num_people": 1,
        "needs": ["food"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "SDRF",
        "has_live_location": true,
        "live_lat": 26.971125,
        "live_lng": 94.5568867,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:56:14.644527+00:00",
        "lat": 26.971125,
        "lng": 94.5568867,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "fdbf354c-5a39-4a7f-ba35-22689f261a98",
        "name": "Bibek gogoi",
        "district": "Sivasagar",
        "location": "Dorikapar hatimuria goan 3no ward ",
        "contact_number": "9957227927",
        "num_people": 62,
        "needs": ["water", "food"],
        "needs_other": "utensils or dishes",
        "priority": "needed",
        "boat_required": false,
        "notes": "Bibek gogoi\\nAkash gogoi\\n",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:40:38.340886+00:00",
        "lat": 27.0109438205392,
        "lng": 94.6632115006087,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "0d80ebe2-2ba1-49c0-a70a-4149053c3c53",
        "name": "Syeda Ashiya Begum ",
        "district": "Sivasagar",
        "location": "Dist: sivsagar Nazira hulang katoni gaon next to railway gate",
        "contact_number": "8486650449",
        "num_people": 4,
        "needs": ["water", "clothes", "medical", "food"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "The situation of our area has improved recently however we are not able to get enough supplies ",
        "has_live_location": true,
        "live_lat": 26.8985912,
        "live_lng": 94.7159061,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:40:34.347+00:00",
        "lat": 26.8985912,
        "lng": 94.7159061,
        "contact_numbers": ["7002737136"],
        "status": "looking"
    },
    {
        "id": "6e75533a-aad3-4902-9472-f84f59c30796",
        "name": "Dipali Das ",
        "district": "Jorhat",
        "location": "BHUYANHAT GAON Jorhat Assam 785680",
        "contact_number": "7896528867",
        "num_people": 2,
        "needs": ["food", "clothes", "water"],
        "needs_other": "Lost home",
        "priority": "urgent",
        "boat_required": false,
        "notes": "Lost home please help ",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:33:01.871464+00:00",
        "lat": 26.7712021532868,
        "lng": 94.2065694602682,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "3bb5f9d8-c87a-4acc-822b-87c5da3be757",
        "name": "Karbi Dihingia ",
        "district": "Sivasagar",
        "location": "Dowari gaon.. Khelua 785701",
        "contact_number": "6900497213",
        "num_people": 1,
        "needs": [],
        "needs_other": null,
        "priority": "needed",
        "boat_required": true,
        "notes": "মোক ঘরটোত থাকিব পরা নামায় গতিকে মোক সহায় করা।বাকি খোরা বস্তু না লাগে।মোর মানুষজনের অখুশিয়া একো করিব নোরারে",
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:31:32.081513+00:00",
        "lat": 26.9914094181118,
        "lng": 94.6064576218819,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "d9b0ab21-ffbd-4bb7-b832-bad7af71e19b",
        "name": "Raj Kishor Patar ",
        "district": "Sivasagar",
        "location": "Banmukh patar gaon ",
        "contact_number": "8453218145",
        "num_people": 4,
        "needs": ["water", "food", "clothes", "medical"],
        "needs_other": "Money",
        "priority": "needed",
        "boat_required": false,
        "notes": "Injured and trapped in a deep drain",
        "has_live_location": true,
        "live_lat": 27.0379354,
        "live_lng": 94.6031589,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:23:19.289302+00:00",
        "lat": 27.0379354,
        "lng": 94.6031589,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "d5fd64f7-0038-4715-b0fb-b0f3aa2778ff",
        "name": "Mazida Begum",
        "district": "Sivasagar",
        "location": "Nazira town.ward no -5",
        "contact_number": "9101685560",
        "num_people": 5,
        "needs": [],
        "needs_other": null,
        "priority": "urgent",
        "boat_required": true,
        "notes": "Mazida Begum.Nazira town ward no.5.9101685560",
        "has_live_location": true,
        "live_lat": 26.9158202,
        "live_lng": 94.7375735,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:17:06.426743+00:00",
        "lat": 26.9158202,
        "lng": 94.7375735,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "6de93e08-d688-4604-b55e-6c0df5aef2bf",
        "name": "Injamul Ali",
        "district": "Sivasagar",
        "location": "Nazira dhapatpotti 5 word",
        "contact_number": "9395247494",
        "num_people": 10,
        "needs": [],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:13:44.479421+00:00",
        "lat": 26.9898680186526,
        "lng": 94.5930498116033,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "456c2181-4b95-4690-83a2-ab8900e86034",
        "name": "Munmun chutia",
        "district": "Sivasagar",
        "location": "Barhoiting bagisa suk",
        "contact_number": "9394837880",
        "num_people": 150,
        "needs": ["water", "food", "clothes", "medical", "sanitation", "baby_care"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": true,
        "live_lat": 27.0457393,
        "live_lng": 94.6216734,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T06:08:09.198665+00:00",
        "lat": 27.0457393,
        "lng": 94.6216734,
        "contact_numbers": ["6900237581"],
        "status": "looking"
    },
    {
        "id": "ce9fc341-140e-4264-a446-2bce23a067f6",
        "name": "Tofikurrahman",
        "district": "Sivasagar",
        "location": "Nazira dhapatpotti word no 5",
        "contact_number": "9678497501",
        "num_people": 4,
        "needs": [],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "Bohi aru school r bag lage horu horu kisuman lora suwali r kapur lage ",
        "has_live_location": true,
        "live_lat": 26.9158736,
        "live_lng": 94.7375442,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T05:56:50.296115+00:00",
        "lat": 26.9158736,
        "lng": 94.7375442,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "49de5cd7-7a65-4a9d-ba8c-81b6adc7a4e1",
        "name": "Tofikurrahman",
        "district": "Sivasagar",
        "location": "Nazira taken we no 5\nSivsagra Nazira taon",
        "contact_number": "9678497501",
        "num_people": 4,
        "needs": [],
        "needs_other": "School bag, copy, and pen pencils",
        "priority": "needed",
        "boat_required": true,
        "notes": null,
        "has_live_location": true,
        "live_lat": 26.9158059,
        "live_lng": 94.7374084,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T05:53:54.104006+00:00",
        "lat": 26.9158059,
        "lng": 94.7374084,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "03f0cf56-2370-4bbd-9c9a-26a913a60d7c",
        "name": "Shilpi Biswakarma ",
        "district": "Sivasagar",
        "location": "Nazira college tiniali\nWard no 3\nNear Bank of India ",
        "contact_number": "9864862460",
        "num_people": 1,
        "needs": ["water"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": "Drinking water shortage ",
        "has_live_location": true,
        "live_lat": 26.9085443,
        "live_lng": 94.7290317,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T05:36:18.756521+00:00",
        "lat": 26.9085443,
        "lng": 94.7290317,
        "contact_numbers": [],
        "status": "looking"
    },
    {
        "id": "d8de9fa1-3c6a-4c5a-b12a-e2869533f41d",
        "name": "Monisha Hazarika ",
        "district": "Jorhat",
        "location": "Khutiya pota gaon ",
        "contact_number": "9394693199",
        "num_people": 100,
        "needs": ["medical", "food"],
        "needs_other": null,
        "priority": "needed",
        "boat_required": false,
        "notes": null,
        "has_live_location": false,
        "live_lat": null,
        "live_lng": null,
        "helper_name": null,
        "helper_from": null,
        "helper_eta_minutes": null,
        "helper_en_route_at": null,
        "hidden": false,
        "created_at": "2026-08-02T05:09:57.880482+00:00",
        "lat": 26.7785995312769,
        "lng": 94.1714315936771,
        "contact_numbers": [],
        "status": "looking"
    }
]`; // Clean JSON string

const parsed = JSON.parse(dataStr);

const sqlStmts = [];
sqlStmts.push('INSERT INTO victim_requests (id, created_at, name, phone, alt_phone, people_count, district, village_name, latitude, longitude, is_urgent_rescue, needs, details, status, ground_condition, urgency) VALUES');

const values = parsed.map(item => {
    // Map fields safely
    const escapeStr = (s) => typeof s === 'string' ? "'" + s.replace(/'/g, "''") + "'" : 'NULL';
    
    const id = escapeStr(item.id);
    const created_at = escapeStr(item.created_at);
    const name = escapeStr(item.name);
    const phone = escapeStr(item.contact_number);
    const alt_phone = (item.contact_numbers && item.contact_numbers.length > 0) ? escapeStr(item.contact_numbers[0]) : 'NULL';
    
    const people_count = item.num_people || 0;
    const district = escapeStr(item.district);
    const village_name = escapeStr(item.location);
    
    const lat = item.lat !== null ? item.lat : (item.live_lat !== null ? item.live_lat : 'NULL');
    const lng = item.lng !== null ? item.lng : (item.live_lng !== null ? item.live_lng : 'NULL');
    
    const is_urgent_rescue = item.boat_required ? 'TRUE' : 'FALSE';
    
    const needsArr = item.needs || [];
    if (item.needs_other) needsArr.push(item.needs_other);
    const needsJson = needsArr.length > 0 ? escapeStr(JSON.stringify(needsArr)) : "NULL";
    
    const details = escapeStr(item.notes);
    const status = escapeStr(item.status || 'PENDING');
    
    let urgency = 'HIGH';
    if (item.priority === 'needed') urgency = 'MEDIUM';
    else if (item.priority === 'low') urgency = 'LOW';
    
    const ground_condition = item.boat_required ? 'SUBMERGED' : 'RECEDING';
    
    return `(${id}, ${created_at}, ${name}, ${phone}, ${alt_phone}, ${people_count}, ${district}, ${village_name}, ${lat}, ${lng}, ${is_urgent_rescue}, ${needsJson}, ${details}, ${status}, '${ground_condition}', '${urgency}')`;
});

fs.writeFileSync('insert_data.sql', sqlStmts[0] + '\n' + values.join(',\n') + ';');
console.log('Done writing insert_data.sql');
